name: My Workflow Name

on:
  push:
    branches:
      - test
      - 4epenaxa-patch-1
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Возможность ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest  # Или указывай конкретную версию

    - name: Install kubectl
      run: |
        sudo snap install kubectl --classic

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Install Cloud Provider Plugin
      run: |
        cd \
        && curl -L --create-dirs -o .terraform.d/plugins/cloud.ru/cloudru/cloud/1.6.0/linux_amd64/terraform-provider-cloud_1.6.0_linux_amd64 \
        https://github.com/CLOUDdotRu/evo-terraform/releases/download/1.6.0/terraform-provider-cloud_1.6.0_linux_amd64 \
        && chmod +x .terraform.d/plugins/cloud.ru/cloudru/cloud/1.6.0/linux_amd64/terraform-provider-cloud_1.6.0_linux_amd64

    - name: Install Cloud Login Tool
      run: |
        curl -LO https://github.com/cloud-ru-tech/cloudlogin/releases/download/v1.0.2/cloudlogin_Linux_amd64.tar.gz
        tar -xzf cloudlogin_Linux_amd64.tar.gz
        sudo mv cloudlogin /usr/local/bin/

    - name: Create .env file
      run: |
        echo "CLOUDRU_KEY_ID=${{ secrets.AUTH_KEY_ID }}" >> terraform-evolution/.env
        echo "CLOUDRU_SECRET_ID=${{ secrets.AUTH_SECRET }}" >> terraform-evolution/.env
    
    - name: Create terraform.tfvars file
      run: |
        echo "auth_key_id=\"${{ secrets.AUTH_KEY_ID }}\"" >> terraform-evolution/terraform.tfvars
        echo "auth_secret=\"${{ secrets.AUTH_SECRET }}\"" >> terraform-evolution/terraform.tfvars
        echo "project_id=\"${{ secrets.PROJECT_ID }}\"" >> terraform-evolution/terraform.tfvars
        echo "customer_id=\"${{ secrets.CUSTOMER_ID }}\"" >> terraform-evolution/terraform.tfvars

    # - name: Prepare additional soft
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y jq gettext-base
    
    - name: Execute custom script
      run: |
        terraform -chdir=terraform-evolution init
        terraform -chdir=terraform-evolution apply -auto-approve
        terraform -chdir=terraform-evolution output -json kubeconfig | sed '1d' | jq -r '.raw' | base64 --decode > temp.yaml
        cat .env
        set -a
        source .env
        set +a
        KEY_ID="$CLOUDRU_KEY_ID"
        SECRET_ID="$CLOUDRU_SECRET_ID"
        echo ""
        echo ""
        echo "SUCCESS ${KEY_ID}"
        
    - name: Send Success Notification
      if: success()
      run: |
        curl -s -X POST https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage \
          -d chat_id=${{vars.TG_AKSYUTA}} \
          -d text="✅ Установка произведена успешно"

    - name: Send Failure Notification
      if: failure()
      run: |
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ vars.TG_AKSYUTA }} \
          -d text="❗️ Установка НЕ произошла"
          
    - name: Execute Terraform destroy
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo "🚀 Terraform destroy"
        terraform -chdir=terraform-evolution destroy -auto-approve
        echo "🎉 Destroying completed successfully"
          
